import CategoryBadge   from "./CategoryBadge"
import UrgencyBadge    from "./UrgencyBadge"
import DraftReply      from "./DraftReply"
import SourceList      from "../shared/SourceList"
import ConfidenceBadge from "../shared/ConfidenceBadge"

function Section({ title, subtitle, children }) {
  return (
    <div className="glass rounded-2xl"
      style={{ border: "1px solid rgba(34,211,238,0.08)", overflow: "hidden" }}>
      {/* Section header */}
      <div style={{ padding: "1.125rem 1.5rem", borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
        <p style={{ fontFamily: "Outfit, sans-serif", fontWeight: 700, fontSize: "1rem",
          color: "var(--text-primary)", marginBottom: subtitle ? "0.25rem" : 0 }}>
          {title}
        </p>
        {subtitle && (
          <p style={{ fontSize: "0.78rem", color: "var(--text-muted)" }}>{subtitle}</p>
        )}
      </div>
      {/* Section body */}
      <div style={{ padding: "1.25rem 1.5rem" }}>
        {children}
      </div>
    </div>
  )
}

export default function TicketResult({ result }) {
  if (!result) return null

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}
      className="animate-fade-up">

      {/* Status bar */}
      <div className="glass rounded-2xl"
        style={{ padding: "1rem 1.5rem", border: "1px solid rgba(34,211,238,0.1)",
          display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: "0.75rem" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.625rem" }}>
          <CategoryBadge category={result.category} />
          <UrgencyBadge  urgency={result.urgency}  />
        </div>
        <ConfidenceBadge level={result.confidence} />
      </div>

      {/* AI Analysis */}
      <Section
        title="AI Analysis"
        subtitle="Category, urgency, and a concise summary generated by the triage model.">
        {result.ask_clarification ? (
          <div style={{ background: "rgba(251,191,36,0.08)", border: "1px solid rgba(251,191,36,0.25)",
            borderRadius: "0.875rem", padding: "1rem 1.25rem", color: "#fbbf24", fontSize: "0.875rem" }}>
            ⚠️ KB did not have enough info — the reply below asks the customer for clarification.
          </div>
        ) : (
          <p style={{ fontSize: "0.9rem", lineHeight: 1.75, color: "var(--text-primary)" }}>
            {result.summary}
          </p>
        )}

        {/* Metadata row */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: "1.25rem", marginTop: "1.25rem",
          paddingTop: "1rem", borderTop: "1px solid rgba(255,255,255,0.05)" }}>
          {[
            { label: "Language",  value: result.metadata?.language?.toUpperCase() },
            { label: "Channel",   value: result.metadata?.channel },
            { label: "Sentiment", value: result.metadata?.sentiment_score?.toFixed(2) },
            { label: "Time",      value: `${result.metadata?.processing_time_ms}ms` },
          ].map(m => (
            <div key={m.label} style={{ display: "flex", alignItems: "center", gap: "0.4rem" }}>
              <span style={{ fontSize: "0.78rem", color: "var(--text-muted)" }}>{m.label}:</span>
              <span style={{ fontSize: "0.78rem", fontWeight: 600, color: "var(--accent-teal)",
                fontFamily: "JetBrains Mono, monospace" }}>{m.value}</span>
            </div>
          ))}
        </div>
      </Section>

      {/* Suggested Reply */}
      <Section
        title="Suggested Reply"
        subtitle="Grounded response generated from the retrieved knowledge base documents.">
        <DraftReply reply={result.draft_reply} />
      </Section>

      {/* Sources */}
      <Section
        title="Sources"
        subtitle="Top knowledge base articles retrieved by embeddings, sorted by similarity.">
        {result.sources?.length > 0
          ? <SourceList sources={result.sources} />
          : <p style={{ fontSize: "0.85rem", color: "var(--text-muted)" }}>
              No KB sources retrieved.
            </p>
        }
      </Section>

    </div>
  )
}