import { useState } from "react"
import { useTriage }  from "../../hooks/useTriage"
import TicketResult   from "./TicketResult"
import LoadingSpinner from "../shared/LoadingSpinner"
import ErrorBanner    from "../shared/ErrorBanner"

const CHANNELS = [
  { id: "email", label: "Email",  hint: "Low urgency",    color: "#4ade80" },
  { id: "chat",  label: "Chat",   hint: "Medium urgency", color: "#fbbf24" },
  { id: "phone", label: "Phone",  hint: "High urgency",   color: "#f87171" },
]

const PLACEHOLDER_SECTIONS = [
  {
    icon: "🧠",
    title: "AI Analysis",
    subtitle: "Category, urgency, and a concise summary generated by the triage model.",
    accentColor: "#22d3ee",
    bgColor: "rgba(34,211,238,0.04)",
    borderColor: "rgba(34,211,238,0.12)",
  },
  {
    icon: "💬",
    title: "Suggested Reply",
    subtitle: "Grounded response generated from the retrieved knowledge base documents.",
    accentColor: "#14b8a6",
    bgColor: "rgba(20,184,166,0.04)",
    borderColor: "rgba(20,184,166,0.12)",
  },
  {
    icon: "📚",
    title: "Sources",
    subtitle: "Top knowledge base articles retrieved by embeddings, sorted by similarity.",
    accentColor: "#818cf8",
    bgColor: "rgba(129,140,248,0.04)",
    borderColor: "rgba(129,140,248,0.12)",
  },
]

const inputStyle = {
  width: "100%",
  borderRadius: "0.875rem",
  padding: "0.875rem 1.125rem",
  fontSize: "0.9rem",
  background: "rgba(255,255,255,0.05)",
  border: "1.5px solid rgba(34,211,238,0.25)",
  color: "var(--text-primary)",
  outline: "none",
  fontFamily: "Outfit, sans-serif",
  transition: "border-color 0.2s, box-shadow 0.2s",
  boxShadow: "0 2px 8px rgba(34,211,238,0.06)",
}

const labelStyle = {
  display: "block",
  fontFamily: "Outfit, sans-serif",
  fontWeight: 700,
  fontSize: "0.68rem",
  letterSpacing: "0.12em",
  textTransform: "uppercase",
  color: "var(--text-muted)",
  marginBottom: "0.625rem",
}

export default function TicketForm() {
  const { submit, result, loading, error, reset } = useTriage()
  const [subject,     setSubject]     = useState("")
  const [description, setDescription] = useState("")
  const [channel,     setChannel]     = useState("email")

  const activeChannel = CHANNELS.find(c => c.id === channel)

  const handleSubmit = () => {
    if (!subject.trim() || !description.trim()) return
    submit({ subject, description, channel })
  }

  const handleReset = () => {
    reset()
    setSubject("")
    setDescription("")
    setChannel("email")
  }

  if (result) return (
    <div className="animate-fade-up"
      style={{ maxWidth: "52rem", margin: "0 auto" }}>
      <div style={{
        display: "flex", alignItems: "center",
        justifyContent: "space-between", marginBottom: "1.75rem"
      }}>
        <h2 style={{
          fontFamily: "Outfit, sans-serif", fontWeight: 800, fontSize: "1.5rem",
          background: "linear-gradient(135deg, #22d3ee, #14b8a6)",
          WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent"
        }}>
          Triage Result
        </h2>
        <button onClick={handleReset} className="glass glass-hover"
          style={{
            fontSize: "0.85rem", padding: "0.5rem 1.25rem",
            borderRadius: "0.75rem", color: "var(--accent-cyan)",
            border: "1px solid rgba(34,211,238,0.2)",
            cursor: "pointer", fontFamily: "Outfit, sans-serif", fontWeight: 600
          }}>
          ← New Ticket
        </button>
      </div>
      <TicketResult result={result} />
    </div>
  )

  return (
    <div className="animate-fade-up"
      style={{
        maxWidth: "52rem", margin: "0 auto",
        display: "flex", flexDirection: "column", gap: "1.5rem"
      }}>

      {/* ── Form card ── */}
      <div className="glass rounded-2xl card-shadow"
        style={{ padding: "2.25rem", border: "1px solid rgba(34,211,238,0.1)" }}>

        <h2 style={{
          fontFamily: "Outfit, sans-serif", fontWeight: 800, fontSize: "1.5rem",
          background: "linear-gradient(135deg, #22d3ee, #14b8a6)",
          WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent",
          marginBottom: "2rem"
        }}>
          Submit Support Ticket
        </h2>

        {/* Subject */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Subject</label>
          <input
            value={subject}
            onChange={e => setSubject(e.target.value)}
            placeholder="e.g. Charged twice for order #4521"
            style={inputStyle}
            onFocus={e => {
              e.target.style.borderColor = "rgba(34,211,238,0.7)"
              e.target.style.boxShadow   = "0 0 0 3px rgba(34,211,238,0.12)"
            }}
            onBlur={e => {
              e.target.style.borderColor = "rgba(34,211,238,0.35)"
              e.target.style.boxShadow   = "0 2px 8px rgba(34,211,238,0.08)"
            }}
          />
        </div>

        {/* Description */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={labelStyle}>Description</label>
          <textarea
            value={description}
            onChange={e => setDescription(e.target.value)}
            placeholder="Describe the issue in detail..."
            rows={6}
            style={{ ...inputStyle, resize: "none", lineHeight: 1.75 }}
            onFocus={e => {
              e.target.style.borderColor = "rgba(34,211,238,0.7)"
              e.target.style.boxShadow   = "0 0 0 3px rgba(34,211,238,0.12)"
            }}
            onBlur={e => {
              e.target.style.borderColor = "rgba(34,211,238,0.35)"
              e.target.style.boxShadow   = "0 2px 8px rgba(34,211,238,0.08)"
            }}
          />
        </div>

        {/* Channel */}
        <div style={{ marginBottom: "2rem" }}>
          <div style={{
            display: "flex", alignItems: "center",
            justifyContent: "space-between", marginBottom: "0.625rem"
          }}>
            <label style={{ ...labelStyle, marginBottom: 0 }}>Channel</label>
            <span style={{ fontSize: "0.82rem", fontWeight: 600, color: activeChannel?.color }}>
              {activeChannel?.hint}
            </span>
          </div>
          <div style={{ display: "flex", gap: "0.75rem" }}>
            {CHANNELS.map(c => (
              <button key={c.id} onClick={() => setChannel(c.id)}
                style={{
                  flex: 1, padding: "0.8rem",
                  borderRadius: "0.875rem",
                  fontSize: "0.875rem", fontWeight: 600,
                  fontFamily: "Outfit, sans-serif",
                  cursor: "pointer", transition: "all 0.2s",
                  background: channel === c.id ? `${c.color}18` : "rgba(255,255,255,0.03)",
                  border: channel === c.id
                    ? `1.5px solid ${c.color}55`
                    : "1.5px solid rgba(34,211,238,0.15)",
                  color: channel === c.id ? c.color : "var(--text-muted)",
                  boxShadow: channel === c.id ? `0 4px 12px ${c.color}20` : "none",
                }}>
                {c.label}
              </button>
            ))}
          </div>
        </div>

        {error && (
          <div style={{ marginBottom: "1.25rem" }}>
            <ErrorBanner message={error} />
          </div>
        )}

        {/* Submit button */}
        <button
          onClick={handleSubmit}
          disabled={loading || !subject.trim() || !description.trim()}
          style={{
            width: "100%", padding: "1rem",
            borderRadius: "0.875rem",
            fontFamily: "Outfit, sans-serif",
            fontWeight: 700, fontSize: "0.95rem",
            letterSpacing: "0.04em",
            cursor: loading || !subject.trim() || !description.trim()
              ? "not-allowed" : "pointer",
            background: loading || !subject.trim() || !description.trim()
              ? "rgba(255,255,255,0.04)"
              : "linear-gradient(135deg, rgba(34,211,238,0.25), rgba(20,184,166,0.25))",
            border: "1.5px solid rgba(34,211,238,0.3)",
            color: loading || !subject.trim() || !description.trim()
              ? "var(--text-muted)" : "var(--accent-cyan)",
            display: "flex", alignItems: "center",
            justifyContent: "center", gap: "0.625rem",
            transition: "all 0.2s",
            boxShadow: !loading && subject.trim() && description.trim()
              ? "0 4px 20px rgba(34,211,238,0.15)" : "none",
          }}>
          {loading
            ? <><LoadingSpinner size={15} /> Analyzing ticket...</>
            : "⚡ Triage Ticket"}
        </button>
      </div>

      {/* ── Placeholder sections ── */}
      {PLACEHOLDER_SECTIONS.map((s) => (
        <div key={s.title} className="glass rounded-2xl card-shadow"
          style={{ border: `1.5px solid ${s.borderColor}`, overflow: "hidden" }}>

          {/* Colored top strip */}
          <div style={{
            height: "3px",
            background: `linear-gradient(90deg, ${s.accentColor}, transparent)`,
          }} />

          {/* Header */}
          <div style={{
            padding: "1.25rem 1.75rem",
            borderBottom: "1px solid rgba(255,255,255,0.05)",
            display: "flex", alignItems: "center", gap: "0.875rem",
            background: s.bgColor,
          }}>
            <div style={{
              width: 38, height: 38, borderRadius: "0.625rem",
              background: `${s.accentColor}15`,
              border: `1px solid ${s.accentColor}30`,
              display: "flex", alignItems: "center",
              justifyContent: "center", fontSize: "1.1rem",
              flexShrink: 0,
            }}>
              {s.icon}
            </div>
            <div>
              <p style={{
                fontFamily: "Outfit, sans-serif", fontWeight: 700,
                fontSize: "1rem", color: s.accentColor
              }}>
                {s.title}
              </p>
              <p style={{
                fontSize: "0.78rem", color: "var(--text-muted)", marginTop: "0.2rem"
              }}>
                {s.subtitle}
              </p>
            </div>
          </div>

          {/* Body */}
          <div style={{ padding: "1.25rem 1.75rem" }}>
            <p style={{
              fontSize: "0.85rem", color: "var(--text-muted)", fontStyle: "italic"
            }}>
              Submit a ticket to see {s.title.toLowerCase()}.
            </p>
          </div>
        </div>
      ))}

    </div>
  )
}